# Generated by Django 5.2 on 2025-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_order_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "movie_session"),
                name="row_seat_session_constraint",
            ),
        ),
    ]
